<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="estilo.css"?>
<!DOCTYPE recetario[
<!ELEMENT recetario (receta+)>
<!ELEMENT receta (nombre_receta,ingredientes,preparacion)>
<!ELEMENT nombre_receta (#PCDATA) >
<!ELEMENT ingredientes (#PCDATA) >
<!ELEMENT preparacion (#PCDATA) >
]>
<recetario>
    <receta>
        <nombre_receta>Pudín de Banana y Chocolate</nombre_receta>
        <ingredientes>    3 bananas. 
            4 cdas. de crema de leche.
            250 g de chocolate untable.</ingredientes>
        <preparacion>
            Pela las bananas y en un recipiente tritúralas con un tenedor.
            Mezcla la crema de leche con el chocolate untable. 
            Añade el "puré de banana" a la mezcla de chocolate.
            Reserva en el refrigerador por una hora y disfruta junto a ellos de una sencilla delicia. 
        </preparacion>
    </receta>
    <receta>
        <nombre_receta>Dip de limón</nombre_receta>
        <ingredientes>    
            El zumo de 4 limones grandes.
            4 cdas. de miel.
            250 g de yogurt griego.
            Rayadura de una cáscara de limón.
        </ingredientes>
        <preparacion>

        </preparacion>
    </receta>    
   
    
</recetario>
